name: Notify Main Repo of Blog Updates

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '!README.md'
      - '!readme.md'

jobs:
  trigger-main-repo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger main repository to update submodule
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/lenielluzardo/lenielluzardo/dispatches \
            -d '{"event_type":"blog-updated"}'
